Remove empty action attributes from vanilla examples to avoid validator errors
canonical-web-and-design/vanilla-framework pull request #3300
Opened 2020-09-22 16:33 UTC by lyubomir-popov

## Done

Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/874

## QA

- Pull code
- Search for action="", verify there are no occurances

2020-09-22 16:33 UTC, webteam-app commented
Demo starting at https://vanilla-framework-3300.demos.haus

2020-09-22 19:26 UTC, bartaz requested changes
Could you clean this branch, please?

Out of three commits in this branch first is from different PR, second one is obsolete, because it's completely replaced by third one.
The only small change needed in this PR is one commit that removes empty action attributes.

<img width="408" alt="Screenshot 2020-09-22 at 21 25 11" src="https://user-images.githubusercontent.com/83575/93928230-46619a00-fd1a-11ea-808e-530f24e2866b.png">

2020-09-23 10:25 UTC, lyubomir-popov commented
Updated.

2020-09-23 11:56 UTC, bartaz approved these changes
LGTM

2020-09-23 11:56 UTC, merged