Add name attribs to form inputs and buttons
canonical-web-and-design/vanilla-framework pull request #3307
Opened 2020-09-24 14:26 UTC by lyubomir-popov

## Done

Fixes https://github.com/canonical-web-and-design/vanilla-squad/issues/867

the name attrib is for server side use - to denote what the value of the input is for as in a key-value pair. So I've limited the additions to only inputs / buttons / selects that look like they are intended for submission, or examples for use as submittable forms. Buttons used for frontend purpouses like toggling states in the ui do not need names as far as I understand. The name attrib itself is not mandatory.

## QA

- Pull code
- Run `./run`
- Test specifically existing search forms, verify they still work- Go through the list of changes, verify they are sensible and free of typos or ommissions

2020-09-24 14:26 UTC, webteam-app commented
Demo starting at https://vanilla-framework-3307.demos.haus

2020-09-25 06:31 UTC, bartaz commented
Is this intended that they are all checked now?
<img width="900" alt="Screenshot 2020-09-25 at 08 30 31" src="https://user-images.githubusercontent.com/83575/94234166-6dca8980-ff09-11ea-8f54-3f65ccaa54b0.png">

2020-09-25 06:34 UTC, bartaz commented on templates/docs/examples/base/forms/radio-buttons.html
> +  <input type="radio" name="RadioOptions1" id="Radio1" value="option1" checked>
Same question here - should these be individual checkboxes, or single group?

2020-09-25 06:35 UTC, bartaz commented on templates/docs/examples/patterns/forms/tick-comparison.html
> +    <input type="radio" id="radioExampleBase" name="radioExampleBase" name="radioBase">
These radio inputs already had a name, second one was added.

2020-09-25 06:36 UTC, bartaz commented on templates/docs/examples/templates/tick-element-comparison.html
> +          <label for="checkExample0">Checkbox option 2</label>
If it's renamed to 0, label should be updated as well.

2020-09-25 06:37 UTC, bartaz requested changes
There are some open questions about naming radio buttons (should they be unique or in groups).

In some cases names were added to the input that already had name attributes.

2020-09-25 11:25 UTC, lyubomir-popov commented on templates/docs/examples/base/forms/aligned-radio.html
> +    <input type="radio" name="RadioOptions1" id="Radio1" value="option1" checked>
sorry, you're right. Reverted.

2020-09-25 11:29 UTC, lyubomir-popov commented
@bartaz ready for another look

2020-09-25 13:52 UTC, bartaz approved these changes
LGTM, thanks!

2020-09-25 13:53 UTC, merged