Change h3 font-weight to 100
canonical-web-and-design/vanilla-framework pull request #3335
Opened 2020-10-05 10:20 UTC by lyubomir-popov

## Done

Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/3334

## QA

- Inspect files changed. Verify value 300 changed to 100.

Screenshot: 

![image](https://user-images.githubusercontent.com/2741678/95068152-caddf080-06fc-11eb-8bbd-9a59b91322d7.png)

2020-10-05 10:20 UTC, webteam-app commented
Demo starting at https://vanilla-framework-3335.demos.haus

2020-10-05 11:11 UTC, spencerbygraves commented
@lyubomir-popov the difference isn't as pronounced, but this seems to shift the problem down a size.

When h3 is placed above h4 after this change, I wonder if we would we get the same comment?

It doesn't block this PR but something to think about [next cycle](https://github.com/canonical-web-and-design/vanilla-framework/issues/3334).

![image](https://user-images.githubusercontent.com/9105999/95072521-375bee00-0703-11eb-9056-f2734881972e.png)

2020-10-05 11:28 UTC, lyubomir-popov commented
@spencerbygraves I know, the only way to avoid this is to stop using the thin wait unfortunately. 

In order to ensure lower headings have thinner or same thickness contours, the ratio by which we scale them needs to be at least equal to the thickness of weight 300 divided by the thickness of weight 100. That is around 1.9, which would be huge to use as a type scale ratio. I've added more details in the attached [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3334)

2020-10-07 12:09 UTC, bartaz commented
Not sure if we want to address this now, but the change affects large pull quotes:

<img width="873" alt="Screenshot 2020-10-07 at 10 43 43" src="https://user-images.githubusercontent.com/83575/95329119-be959700-08a6-11eb-88b1-ca7a5ecb3c1f.png">

2020-10-07 14:16 UTC, lyubomir-popov commented
@bartaz changed to this:
![image](https://user-images.githubusercontent.com/2741678/95343000-eccba480-08af-11eb-8e8d-ffad86659b57.png) 

@spencerbygraves are you ok with this fix until we have the font weights conversation? 

I'm reducing the font-size of the bylines in quotes to be effectively `h6`'s.

2020-10-07 14:23 UTC, bartaz requested changes
Some changes needed around pull-quote styles

2020-10-07 14:23 UTC, bartaz commented on scss/_patterns_pull-quotes.scss
> +      // font-style: italic;
If we don't need this, it should be removed.

2020-10-07 14:23 UTC, bartaz commented on scss/_patterns_pull-quotes.scss
> +      @extend %vf-heading-6;
Do we wan't the same h6 size for all the variants?

This part of SCSS file is defining common shared styles of all quotes. Specific sizes for all variants are defined below:
line 79 defines size of default variant (as h4)
line 96 defines small variant as default text size
line 114 defines large variant as h3

I don't know why this shared definition of h6 wins in specificity and overrides all of the specific styles defined later.

If we really want the same size for all variants, we should remove individual size definitions below.

2020-10-07 14:54 UTC, bartaz approved these changes
LGTM, thanks

2020-10-07 15:15 UTC, spencerbygraves commented
>are you ok with this fix until we have the font weights conversation?

@lyubomir-popov I think that would mean the large pull quote has a smaller citation than the default one. It should probably be the same size, what do you think?

2020-10-07 15:41 UTC, lyubomir-popov commented
@spencerbygraves no they all have the same h6, I tagged you in percy on the image that shows them all.

2020-10-08 08:42 UTC, merged