Set muted heading font weight to 300
canonical-web-and-design/vanilla-framework pull request #3346
Opened 2020-10-08 15:46 UTC by bartaz

## Done

Fixes #3308

## QA

- Pull code
- Run `./run`
- Open http://0.0.0.0:8101/ or [demo]
- Make sure muted heading renders as expected

2020-10-08 15:46 UTC, webteam-app commented
Demo starting at https://vanilla-framework-3346.demos.haus

2020-10-08 15:48 UTC, lyubomir-popov approved these changes

2020-10-09 07:36 UTC, merged

2020-10-09 07:54 UTC, anthonydillon requested changes
The reason to make this weight a variable and default is to have it editable by consumers. If that is what we want then we should document this variable.

2020-10-09 08:03 UTC, bartaz commented
Fair point @anthonydillon, thanks. Created as #3348