Update the style of back to top link
canonical-web-and-design/vanilla-framework pull request #3696
Opened 2021-04-08 13:57 UTC by bartaz

## Done

[List of work items including drive-bys]

Fixes #3667

## QA

- Open [demo](insert-demo-url)
- [Add QA steps]
- Review updated documentation:
  - [List any updated documentation for review]

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [ ] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical-web-and-design/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [component status page](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/component-status.md).
- [ ] Documentation side navigation should be updated with the relevant labels.

## Screenshots

[if relevant, include a screenshot or screen capture]

2021-04-08 14:23 UTC, lyubomir-popov requested changes

2021-04-08 14:23 UTC, lyubomir-popov commented on scss/_patterns_links.scss
> +    padding: 0 $sph-inner--small;
```suggestion
    padding: 0 $sph-inner--small 0 $sph-inner;
```

2021-04-08 14:23 UTC, lyubomir-popov commented on scss/_patterns_links.scss
> +    margin-top: -$spv-outer--scaleable;
This is risky, if you put a dark strip on top it overlaps it:

![image](https://user-images.githubusercontent.com/2741678/114043438-30629380-987e-11eb-8188-52eb6e6fe3bb.png)

2021-04-08 14:23 UTC, lyubomir-popov commented on scss/_patterns_links.scss
> +    margin-top: -$spv-outer--scaleable;
```suggestion

```

2021-04-09 08:20 UTC, sowasred2012 approved these changes

2021-04-09 08:21 UTC, merged