Add toolbar to the fluid-breakout layout
canonical-web-and-design/vanilla-framework pull request #3716
Opened 2021-04-23 13:38 UTC by solazio

## Done

- Add toolbar to the fluid-breakout layout

Fixes [list issues/bugs if needed]

## QA

- Open [demo](insert-demo-url)
- Go to /docs/layouts/fluid-breakout and see the `toolbar` information makes sense
- Go to /docs/examples/layouts/fluid-breakout/fluid-breakout-left-aside-and-toolbar and see the toolbar example works fine on all screen sizes
- Go to /docs/examples/layouts/fluid-breakout/fluid-breakout-cards-with-aside-and-toolbar and see the layout works fine on all screen sizes
- Review updated documentation:
  - [List any updated documentation for review]

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [ ] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical-web-and-design/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [component status page](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/component-status.md).
- [ ] Documentation side navigation should be updated with the relevant labels.

## Screenshots

[if relevant, include a screenshot or screen capture]

2021-04-23 13:39 UTC, webteam-app commented
Demo starting at https://vanilla-framework-3716.demos.haus

2021-04-23 14:15 UTC, bartaz commented on templates/docs/examples/layouts/fluid-breakout/fluid-breakout-cards-with-aside-and-toolbar.html
> +{% block title %}Fluid breakout - cards with aside and toolbar{% endblock %}
@solazio You renamed this file, but I think the old `fluid-breakout-card-and-aside` is linked from somewhere - likely as an embedded example (https://vanillaframework.io/docs/layouts/fluid-breakout#uses).

So, to keep the old embedded example you would need to keep the old file and just add yours separately.
Or update the documentation page to correctly embed new example.

2021-04-23 14:23 UTC, bartaz requested changes
Thanks @solazio. Couple of changes to make this ready for release.

- you are adding new feature, so we need to change version number in package.json, last released was `2.28.0`, so yours needs to be `2.29.0` (please change that in package.json from `2.28.1` that is there currently)
- any new features should be listed in `component-status.md` table - hopefully it should be pretty clear how to do it, if not, ping us
- changes should be highlighted in side nav as well, you can do it by [editing this line](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/_layouts/docs.html#L120) by adding "updated" as third parameter `side_nav_item("/docs/layouts/fluid-breakout", "Fluid breakout", "updated")`

Thanks!

2021-04-23 14:26 UTC, bartaz commented
Toolbar seems broken in IE:

<img width="1844" alt="Screenshot 2021-04-23 at 16 25 13" src="https://user-images.githubusercontent.com/83575/115885764-8cb5dd80-a450-11eb-8d1c-6497fbffd19e.png">

It doesn't need to work exactly the same, but it should not overlap with sidebar like currently.

2021-04-26 11:58 UTC, sowasred2012 approved these changes
LGTM

2021-04-26 11:58 UTC, merged