Update top left nav logo spacing and selected state
canonical-web-and-design/vanilla-framework pull request #3727
Opened 2021-05-04 08:58 UTC by sowasred2012

## Done

- Adjusted height of top nav logo, and padding around nav items
- Added new selected/hover/active state to top nav, featuring Ubuntu orange

Fixes #3653 

## QA

- Open [default dark nav demo](/docs/examples/patterns/navigation/default-dark)
- Open [default nav demo](/docs/examples/patterns/navigation/default)
- See that the updates comply with the [design](https://app.zeplin.io/project/5ef9d96f06f00111064d6268/screen/6076f590cf53b53d0add509c)

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [x] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [x] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical-web-and-design/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [x] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [component status page](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/component-status.md).
- [x] Documentation side navigation should be updated with the relevant labels.

2021-05-04 08:58 UTC, webteam-app commented
Demo starting at https://vanilla-framework-3727.demos.haus

2021-05-07 12:27 UTC, fitojb commented
This looks awesome.

2021-05-19 11:05 UTC, bartaz commented
seems like subnav was not aligned with new height:

![Uploading Screenshot 2021-05-19 at 13.00.16.png…]()

2021-05-19 11:50 UTC, lyubomir-popov commented
@bartaz your image didn't upload properly and I'm not sure what you mean - both are 56px high:
![image](https://user-images.githubusercontent.com/2741678/118807770-9fc99b00-b8a0-11eb-8575-9c0abe706562.png)
![image](https://user-images.githubusercontent.com/2741678/118807813-ab1cc680-b8a0-11eb-87f8-20f9c76b7113.png)

2021-05-20 08:08 UTC, bartaz requested changes
Small typo to fix, but looks good otherwise.

2021-05-20 08:37 UTC, lyubomir-popov commented on scss/_global_functions.scss
> +@mixin vf-highlight-bar($bg-color: $color-mid-dark, $position: top, $over-border: false, $horisontal-padding: 0) {
oops it is z in british spelling too, my bad. will fix

2021-05-20 09:18 UTC, bartaz approved these changes
LGTM

2021-05-20 09:59 UTC, merged