Updated switch styling
canonical-web-and-design/vanilla-framework pull request #4254
Opened 2022-01-18 11:00 UTC by mtruj013

## Done

Updated switch styling as per [visual update](https://app.zenhub.com/workspaces/-design-system-tribe-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/4036)

Fixes https://github.com/canonical-web-and-design/vanilla-framework/issues/4249

## QA

- Open [demo](insert-demo-url)
- See the the styling changes have been made accurately 

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [ ] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical-web-and-design/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical-web-and-design/vanilla-framework/blob/main/templates/docs/whats-new.md).
- [ ] Documentation side navigation should be updated with the relevant labels.

## Screenshots

![Screenshot 2022-01-18 at 11 59 11](https://user-images.githubusercontent.com/17607612/149924798-3f5d57ba-56cd-4f2b-a7f3-2022dfb03510.png)

2022-01-18 11:00 UTC, webteam-app commented
Demo starting at https://vanilla-framework-4254.demos.haus

2022-01-18 11:32 UTC, bartaz commented on scss/_patterns_switch.scss
> +    border-radius: .7rem;
```suggestion
    border-radius: math.div($knob-size, 2);
```

And add `@use sass:math;`

2022-01-18 11:50 UTC, bartaz approved these changes

2022-01-18 12:23 UTC, bartaz commented on scss/_patterns_switch.scss
>      height: $knob-size;
It seems on designs the handle is 16px (1rem).

2022-01-18 12:33 UTC, bartaz commented
There seem to be a border around the handle (in switched off option) and blue border in switched on.
Also switched off version seems to have bit darker background than implemented (the same as slider grey?):

![Screenshot 2022-01-18 at 13.26.19.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/afd178d2-dc0c-48c4-a86c-81de90e29921)

![Screenshot 2022-01-18 at 13.32.09.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/fa001536-dedc-4fe8-b482-5fa459b82bcc)

2022-01-19 08:21 UTC, bartaz requested changes
Some adjustments for the `$knob-size` variable needed.

2022-01-19 08:21 UTC, bartaz commented on scss/_patterns_switch.scss
> +$knob-size: $sp-unit;
Sorry to bother about this again, but you are doing a lot of multiplications when this is too small.

I'd suggest using 
```suggestion
$knob-size: $sp-unit * 2;
```

Which will be 1rem, and expected knob-size.

Then in all places where you need the knob-size you can just use this variable directly. And for the width of the switch multiply it by 2.

2022-01-19 08:21 UTC, bartaz commented on scss/_patterns_switch.scss
> +    height: $knob-size * 2;
`$knob-size` variable should already have the value needed here, as in comment above.

```suggestion
    height: $knob-size;
```

2022-01-19 08:21 UTC, bartaz commented on scss/_patterns_switch.scss
> +    width: $knob-size * 4;
```suggestion
    width: $knob-size * 2;
```

2022-01-19 08:21 UTC, bartaz commented on scss/_patterns_switch.scss
> +      height: $knob-size * 2;
```suggestion
      height: $knob-size;
```

2022-01-19 08:21 UTC, bartaz commented on scss/_patterns_switch.scss
> +      width: $knob-size * 2;
```suggestion
      width: $knob-size;
```

2022-01-19 08:21 UTC, bartaz commented on scss/_patterns_switch.scss
> +    border-radius: $knob-size * 1.5;
Should the border radius here just equal the size of the handle?
```suggestion
    border-radius: $knob-size;
```

2022-01-19 08:59 UTC, bartaz commented on scss/_patterns_switch.scss
> -      left: 0;
Why is this removed? I think that's what has affected the animation.

2022-01-19 09:54 UTC, lyubomir-popov commented
Looks great.

2022-01-19 10:19 UTC, bartaz approved these changes
LGTM, thanks!

2022-01-19 10:22 UTC, merged