4383 top nav adjustments
canonical-web-and-design/vanilla-framework pull request #4386
Opened 2022-03-31 11:13 UTC by bethcollins92

## Done

- Update deprecated example to include more features
- Adjust the size of the top nav bar from `3.5rem` to `3rem` on small screens as per [design](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=0%3A1832)
- Make the highlight the same as text instead of ubuntu orange

Fixes #4383 

## QA

- Open [demo](insert-demo-url)
- Review the deprecated examples check they work as expeced
- Check the highlight colour of the top nav is correct on light and dark themes
- Check on mobile the height of the top nav is correct (3rem)

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [x] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [x] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical-web-and-design/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical-web-and-design/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [x] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical-web-and-design/vanilla-framework/blob/main/templates/docs/whats-new.md).
- [x] Documentation side navigation should be updated with the relevant labels.

## Screenshots

![Screenshot 2022-03-31 at 12 11 51](https://user-images.githubusercontent.com/58959073/161042442-c69cd090-1aaf-4240-8cc9-0c178a215726.png)
![Screenshot 2022-03-31 at 12 12 16](https://user-images.githubusercontent.com/58959073/161042495-18689c87-85dd-420c-a251-b5d28ad28d24.png)

2022-03-31 11:13 UTC, webteam-app commented
Demo starting at https://vanilla-framework-4386.demos.haus

2022-04-01 11:39 UTC, lyubomir-popov commented
Looks great, thanks.

2022-04-04 08:23 UTC, bartaz commented
Not sure why Percy is auto approved, there have been some small issues.

Deprecated example seems to be misaligned:
<img width="471" alt="Screenshot 2022-04-04 at 10 20 35" src="https://user-images.githubusercontent.com/83575/161503666-0e3fb10a-e92a-4dc3-90a0-f99d105b0457.png">

First of all, this example should not have new logo (dark one).
Top example with old logo doesn't get smaller on mobile screens. "Menu" button is smaller but whole nav not (so button is misaligned).
This happens also in "Search box - Navigation" and "Search box - Navigation dark" examples, because they use current navigation component as well.

2022-04-04 10:20 UTC, bartaz requested changes
Some comments to address

2022-04-04 10:20 UTC, bartaz commented on scss/_patterns_navigation.scss
> +    @media (max-width: $breakpoint-navigation-threshold) {
Ideally we should do this other way around (mobile first), so by default smaller spacing, and `min-width` breakpoint to turn it into desktop view.

2022-04-04 10:20 UTC, bartaz commented on scss/_patterns_navigation.scss
> +      @media (max-width: $breakpoint-navigation-threshold) {
Ideally we should do this other way around (mobile first), so by default smaller spacing, and `min-width` breakpoint to turn it into desktop view.

2022-04-04 10:20 UTC, bartaz commented on templates/docs/examples/patterns/navigation/deprecated.html
> +      <div class="p-navigation__tagged-logo">
Why are we using new logo in the "deprecated" navigation?

2022-04-05 13:38 UTC, merged